var files =
[
    [ "Backpropagation.cpp", "_backpropagation_8cpp_source.html", null ],
    [ "Backpropagation.h", "_backpropagation_8h_source.html", null ],
    [ "BackpropagationConfig.cpp", "_backpropagation_config_8cpp_source.html", null ],
    [ "BackpropagationConfig.h", "_backpropagation_config_8h_source.html", null ],
    [ "ConfigBase.cpp", "_config_base_8cpp_source.html", null ],
    [ "ConfigBase.h", "_config_base_8h_source.html", null ],
    [ "DataContainer.cpp", "_data_container_8cpp_source.html", null ],
    [ "DataContainer.h", "_data_container_8h_source.html", null ],
    [ "Enums.cpp", "_enums_8cpp_source.html", null ],
    [ "Enums.h", "_enums_8h_source.html", null ],
    [ "Function.cpp", "_function_8cpp_source.html", null ],
    [ "Functions.h", "_functions_8h_source.html", null ],
    [ "GeneticAlgorithm.cpp", "_genetic_algorithm_8cpp_source.html", null ],
    [ "GeneticAlgorithm.h", "_genetic_algorithm_8h_source.html", null ],
    [ "GeneticAlgorithmConfig.cpp", "_genetic_algorithm_config_8cpp_source.html", null ],
    [ "GeneticAlgorithmConfig.h", "_genetic_algorithm_config_8h_source.html", null ],
    [ "Helper.cpp", "_helper_8cpp_source.html", null ],
    [ "Helper.h", "_helper_8h_source.html", null ],
    [ "Layer.cpp", "_layer_8cpp_source.html", null ],
    [ "Layer.h", "_layer_8h_source.html", null ],
    [ "main.cpp", "main_8cpp_source.html", null ],
    [ "NeuralNetwork.cpp", "_neural_network_8cpp_source.html", null ],
    [ "NeuralNetwork.h", "_neural_network_8h_source.html", null ],
    [ "NeuralNetworkConfig.cpp", "_neural_network_config_8cpp_source.html", null ],
    [ "NeuralNetworkConfig.h", "_neural_network_config_8h_source.html", null ],
    [ "NeuralNetworkMeasure.h", "_neural_network_measure_8h_source.html", null ],
    [ "Neuron.cpp", "_neuron_8cpp_source.html", null ],
    [ "Neuron.h", "_neuron_8h_source.html", null ],
    [ "TrainerBase.cpp", "_trainer_base_8cpp_source.html", null ],
    [ "TrainerBase.h", "_trainer_base_8h_source.html", null ]
];